#############################################
#     || MYTHIC BOSSES config.yml ||
#############################################

# IMPORTANT: Must copy the mobs you want to be considered as bosses in here.

# enabled - if boss should be enabled
# interval - time (in seconds) which they will spawn in the locations specified below.
# spawnChance - chances of the boss spawning
# locations - locations to spawn the boss.

bosses:
  SkeletalKnight:
    enabled: true
    interval: 60
    spawnChance: 30
    locations:
      - 'world,-240,60,204'
  SkeletonKing:
    enabled: true
    interval: 60
    spawnChance: 30
    locations:
      - 'world,-240,60,204'

# pre_announce_time - time (in seconds) to announce pre_announcement message from messages.yml.
pre_announce_time: 30