#############################################
#     || MYTHIC BOSSES config.yml ||
#############################################

# Must copy the mobs you want to be considered as bosses in here.
# interval: # time (in seconds) which they will spawn in the locations specified below.
# locations # locations to spawn the boss.

bosses:
  SkeletalKnight:
    enabled: true
    interval: 60
    spawnChance: 30
    locations:
      - 'world,-240,60,204'
  SkeletonKing:
    enabled: true
    interval: 60
    spawnChance: 30
    locations:
      - 'world,-240,60,204'
  StaticallyChargedSheep:
    enabled: true
    interval: 60
    spawnChance: 30
    locations:
      - 'world,-240,60,204'
  AngrySludge:
    enabled: true
    interval: 60
    spawnChance: 30
    locations:
      - 'world,-240,60,204'